apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookify-client-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nayem9b/sheba-CD.git'
    targetRevision: HEAD
    path: Server/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true