apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-backend
spec:
  selector:
    matchLabels:
      app: sheba-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sheba-backend
    namespace: sheba
    spec:
      containers:
      - name: sheba-backend
        image: nayem9b/sheba-backend-github-build
        ports:
        - containerPort: 3000
        - containerPort: 4000
