apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-backend
spec:
  selector:
    matchLabels:
      app: sheba-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: sheba-backend
    namespace: sheba
    spec:
      containers:
      - name: sheba-backend
        image: nayem9b/sheba-backend-github-build:latest
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: sheba-config
              key: NODE_ENV
        - name: PORT 
          valueFrom:
            configMapKeyRef:
              name: sheba-config
              key: PORT
        - name: JWT_ACCESS_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: sheba-config
              key: JWT_ACCESS_EXPIRES_IN
        - name: JWT_REFRESH_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: sheba-config
              key: JWT_REFRESH_EXPIRES_IN
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        - containerPort: 4000
