---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-backend
  namespace: sheba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheba-backend
  template:
    metadata:
      labels:
        app: sheba-backend
    spec:

      initContainers:
        - name: prisma-migrate
          image: nayem9b/sheba-backend-github-build:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "🔄 Running Prisma migration...";
              npx prisma migrate deploy --schema=./prisma/schema.prisma;
              echo "✅ Migration completed.";
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-db-secret
                  key: DATABASE_URL


      containers:
        - name: sheba-backend
          image: nayem9b/sheba-backend-github-build:latest
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              echo "🚀 Starting server...";
              yarn start;
          ports:
            - containerPort: 3000
            - containerPort: 4000
          env:
            # --- ConfigMap Vars ---
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: PORT
            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: JWT_ACCESS_EXPIRES_IN
            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                configMapKeyRef:
                  name: sheba-backend-config
                  key: JWT_REFRESH_EXPIRES_IN

            # --- Secret Vars ---
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: DATABASE_URL
            - name: BCRYPT_SALT_ROUNDS
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: BCRYPT_SALT_ROUNDS
            - name: ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: ACCESS_SECRET
            - name: REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: REFRESH_SECRET
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_SECRET_KEY
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_PUBLISHABLE_KEY
            - name: CLERK_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: CLERK_API_URL
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: WEBHOOK_SECRET
            - name: AWS_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: AWS_ACCESS_ID
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: AWS_ACCESS_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: JWT_SECRET
            - name: SSL_BASE_PAYMENT_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: SSL_BASE_PAYMENT_URL
            - name: STORE_ID
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: STORE_ID
            - name: SSL_BASE_VALIDATION_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: SSL_BASE_VALIDATION_URL
            - name: STORE_PASS
              valueFrom:
                secretKeyRef:
                  name: sheba-backend-secret
                  key: STORE_PASS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheba-frontend
  namespace: sheba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheba-frontend
  template:
    metadata:
      labels:
        app: sheba-frontend
    spec:
      containers:
        - name: sheba-frontend
          image: nayem9b/sheba-frontend-github-build:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: sheba-frontend-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: sheba-frontend-config
                  key: PORT
            - name: CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: CLERK_PUBLISHABLE_KEY
            - name: CLERK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: CLERK_SECRET_KEY
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: NEXTAUTH_URL
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            - name: IMG_BB_KEY
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: IMG_BB_KEY
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              valueFrom:
                secretKeyRef: 
                  name: sheba-frontend-secret
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
            - name: adminpass
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: adminpass
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: WEBHOOK_SECRET
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: GOOGLE_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: sheba-frontend-secret
                  key: GOOGLE_SECRET
