apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080